In [1]:
import pandas as pd

In [2]:
df=pd.read_excel("world_cup_standard_stats(1).xlsx")

FileNotFoundError: [Errno 2] No such file or directory: 'world_cup_standard_stats(1).xlsx'

In [3]:
df = pd.read_excel("world_cup_standard_stats (1).xlsx")

In [4]:
df.head()

,Rk,Player,Pos,Squad,Age,Club,Born,MP,Starts,Min,...,CrdY,CrdR,Gls.1,Ast.1,G+A.1,G-PK.1,G+A-PK,Matches,-9999,Group
0,1,Brenden Aaronson,MF,us USA,25,1.eng Leeds United,2000,1,1,76,...,0,0,0.0,0.0,0.0,0.0,0.0,Matches,5bc43860,Starter
1,2,Thelo Aasgaard,MF,no Norway,24,1.sct Rangers,2002,1,1,90,...,0,0,1.0,0.0,1.0,1.0,1.0,Matches,c88a28b9,Starter
2,3,Hamza Abdelkarim,FW,eg Egypt,18,4.es Barcelona B,2008,4,0,60,...,0,0,0.0,0.0,0.0,0.0,0.0,Matches,057d8f12,NaN
3,4,Hossam Abdelmaguid,DF,eg Egypt,25,1.eg Zamalek SC,2001,2,0,59,...,0,0,0.0,0.0,0.0,0.0,0.0,Matches,accbfc94,NaN
4,5,Mohamed Abdelmonem,DF,eg Egypt,27,1.fr Nice,1999,2,1,14,...,0,0,0.0,0.0,0.0,0.0,0.0,Matches,bff15d74,NaN

In [5]:
df["Group"].value_counts()

Group
Starter       345
Substitute    164
Name: count, dtype: int64

In [6]:
starters = df[df["Group"] == "Starter"].sample(n=50, random_state=42)

substitutes = df[df["Group"] == "Substitute"].sample(n=50, random_state=42)

sample100 = pd.concat([starters, substitutes])

In [7]:
sample100["Group"].value_counts()

Group
Starter       50
Substitute    50
Name: count, dtype: int64

In [8]:
sample100.groupby("Group")["Min"].describe()

            count    mean         std   min     25%    50%     75%    max
Group
Starter      50.0  250.96  130.037351  45.0  146.00  239.0  335.50  659.0
Substitute   50.0   28.98   25.291355   1.0   14.25   21.5   41.75  140.0

In [9]:
import scipy.stats as stats
import numpy as np

starter_min = sample100[sample100["Group"] == "Starter"]["Min"]
sub_min = sample100[sample100["Group"] == "Substitute"]["Min"]

starter_ci = stats.t.interval(
    0.95,
    len(starter_min)-1,
    loc=np.mean(starter_min),
    scale=stats.sem(starter_min)
)

sub_ci = stats.t.interval(
    0.95,
    len(sub_min)-1,
    loc=np.mean(sub_min),
    scale=stats.sem(sub_min)
)

print("Starter 95% CI:", starter_ci)
print("Substitute 95% CI:", sub_ci)

Starter 95% CI: (np.float64(214.00379375103032), np.float64(287.9162062489697))
Substitute 95% CI: (np.float64(21.7922763516698), np.float64(36.1677236483302))

In [10]:
t_stat, p_value = stats.ttest_ind(starter_min, sub_min, equal_var=False)

print("T-statistic:", t_stat)
print("P-value:", p_value)

T-statistic: 11.84863011471019
P-value: 1.7577701888519845e-16

In [11]:
sample100.to_excel("final_100_midfielders.xlsx", index=False)

In [12]:
sample100.to_excel("final_100_midfielders.xlsx", index=False)

In [13]:
sample100.head()

,Rk,Player,Pos,Squad,Age,Club,Born,MP,Starts,Min,...,CrdY,CrdR,Gls.1,Ast.1,G+A.1,G-PK.1,G+A-PK,Matches,-9999,Group
595,596,Weston McKennie,MF,us USA,27,1.it Juventus,1998,5,5,443,...,1,0,0.00,0.0,0.00,0.0,0.0,Matches,01c3aff5,Starter
485,486,Dostonbek Khamdamov,MF,uz Uzbekistan,29,1.uz Pakhtakor Tashkent FK,1996,2,1,103,...,0,0,0.00,0.0,0.00,0.0,0.0,Matches,d2dd2ffb,Starter
679,680,Aiden O'Neill,MF,au Australia,27,1.us NYCFC,1998,4,4,360,...,0,0,0.00,0.0,0.00,0.0,0.0,Matches,c7aee75b,Starter
626,627,Teboho Mokoena,MF,za South Africa,29,1.za Sundowns,1997,3,3,270,...,2,0,0.33,0.0,0.33,0.0,0.0,Matches,00029b1e,Starter
964,965,Federico Valverde,MF,uy Uruguay,27,1.es Real Madrid,1998,3,3,236,...,0,0,0.00,0.0,0.00,0.0,0.0,Matches,0959c2a2,Starter

In [14]:
sample100.head()

,Rk,Player,Pos,Squad,Age,Club,Born,MP,Starts,Min,...,CrdY,CrdR,Gls.1,Ast.1,G+A.1,G-PK.1,G+A-PK,Matches,-9999,Group
595,596,Weston McKennie,MF,us USA,27,1.it Juventus,1998,5,5,443,...,1,0,0.00,0.0,0.00,0.0,0.0,Matches,01c3aff5,Starter
485,486,Dostonbek Khamdamov,MF,uz Uzbekistan,29,1.uz Pakhtakor Tashkent FK,1996,2,1,103,...,0,0,0.00,0.0,0.00,0.0,0.0,Matches,d2dd2ffb,Starter
679,680,Aiden O'Neill,MF,au Australia,27,1.us NYCFC,1998,4,4,360,...,0,0,0.00,0.0,0.00,0.0,0.0,Matches,c7aee75b,Starter
626,627,Teboho Mokoena,MF,za South Africa,29,1.za Sundowns,1997,3,3,270,...,2,0,0.33,0.0,0.33,0.0,0.0,Matches,00029b1e,Starter
964,965,Federico Valverde,MF,uy Uruguay,27,1.es Real Madrid,1998,3,3,236,...,0,0,0.00,0.0,0.00,0.0,0.0,Matches,0959c2a2,Starter

In [15]:
sample100

,Rk,Player,Pos,Squad,Age,Club,Born,MP,Starts,Min,...,CrdY,CrdR,Gls.1,Ast.1,G+A.1,G-PK.1,G+A-PK,Matches,-9999,Group
595,596,Weston McKennie,MF,us USA,27,1.it Juventus,1998,5,5,443,...,1,0,0.00,0.0,0.00,0.0,0.0,Matches,01c3aff5,Starter
485,486,Dostonbek Khamdamov,MF,uz Uzbekistan,29,1.uz Pakhtakor Tashkent FK,1996,2,1,103,...,0,0,0.00,0.0,0.00,0.0,0.0,Matches,d2dd2ffb,Starter
679,680,Aiden O'Neill,MF,au Australia,27,1.us NYCFC,1998,4,4,360,...,0,0,0.00,0.0,0.00,0.0,0.0,Matches,c7aee75b,Starter
626,627,Teboho Mokoena,MF,za South Africa,29,1.za Sundowns,1997,3,3,270,...,2,0,0.33,0.0,0.33,0.0,0.0,Matches,00029b1e,Starter
964,965,Federico Valverde,MF,uy Uruguay,27,1.es Real Madrid,1998,3,3,236,...,0,0,0.00,0.0,0.00,0.0,0.0,Matches,0959c2a2,Starter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,256,Ismael Díaz,FWMF,pa Panama,29,1.mx León,1997,2,0,37,...,0,0,0.00,0.0,0.00,0.0,0.0,Matches,f2a276d1,Substitute
544,545,Awer Mabil,FWMF,au Australia,30,2.es Castellón,1995,1,0,30,...,0,0,0.00,0.0,0.00,0.0,0.0,Matches,922da988,Substitute
173,174,İrfan Can Kahveci,MF,tr Türkiye,30,1.tr Kasımpaşa,1995,1,0,1,...,0,0,0.00,0.0,0.00,0.0,0.0,Matches,d2800f47,Substitute
849,850,Ken Sema,FWMF,se Sweden,32,1.cy Pafos FC,1993,1,0,16,...,0,0,0.00,0.0,0.00,0.0,0.0,Matches,1770bd68,Substitute
441,442,Cedric Itten,FWMF,ch Switzerland,29,2.de Düsseldorf,1996,3,0,42,...,0,0,0.00,0.0,0.00,0.0,0.0,Matches,ef233486,Substitute

In [16]:
pd.set_option("display.max_rows", 100)
sample100

,Rk,Player,Pos,Squad,Age,Club,Born,MP,Starts,Min,...,CrdY,CrdR,Gls.1,Ast.1,G+A.1,G-PK.1,G+A-PK,Matches,-9999,Group
595,596,Weston McKennie,MF,us USA,27,1.it Juventus,1998,5,5,443,...,1,0,0.00,0.00,0.00,0.00,0.00,Matches,01c3aff5,Starter
485,486,Dostonbek Khamdamov,MF,uz Uzbekistan,29,1.uz Pakhtakor Tashkent FK,1996,2,1,103,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,d2dd2ffb,Starter
679,680,Aiden O'Neill,MF,au Australia,27,1.us NYCFC,1998,4,4,360,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,c7aee75b,Starter
626,627,Teboho Mokoena,MF,za South Africa,29,1.za Sundowns,1997,3,3,270,...,2,0,0.33,0.00,0.33,0.00,0.00,Matches,00029b1e,Starter
964,965,Federico Valverde,MF,uy Uruguay,27,1.es Real Madrid,1998,3,3,236,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,0959c2a2,Starter
1017,1018,Kenan Yıldız,MF,tr Türkiye,21,1.it Juventus,2005,3,2,218,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,d8cda243,Starter
966,967,Hans Vanaken,MF,be Belgium,33,1.be Club Brugge,1992,6,3,319,...,0,0,0.28,0.56,0.85,0.28,0.85,Matches,392a7aea,Starter
786,787,Antonee Robinson,DFMF,us USA,28,1.eng Fulham,1997,4,4,348,...,1,0,0.00,0.00,0.00,0.00,0.00,Matches,289601000000,Starter
322,323,Jassem Gaber,MF,qa Qatar,24,1.qa Al Rayyan SC,2002,3,3,149,...,1,0,0.00,0.00,0.00,0.00,0.00,Matches,af9ef8aa,Starter
664,665,João Neves,MF,pt Portugal,21,1.fr PSG,2004,5,4,390,...,0,0,0.23,0.00,0.23,0.23,0.23,Matches,c2a15a27,Starter
935,936,Youri Tielemans,MF,be Belgium,29,1.eng Aston Villa,1997,5,5,474,...,0,0,0.38,0.00,0.38,0.19,0.19,Matches,56f7a928,Starter
300,301,Ahmed Fathy,MF,qa Qatar,33,1.qa Al-Arabi,1993,3,1,150,...,2,0,0.00,0.00,0.00,0.00,0.00,Matches,f2369793,Starter
115,116,Aziz Behich,MF,au Australia,35,1.au Melb City,1990,3,2,217,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,b6867b96,Starter
264,265,Ritsu Doan,MF,jp Japan,27,1.de Frankfurt,1998,4,4,278,...,0,0,0.00,0.32,0.32,0.00,0.32,Matches,d01bbb6f,Starter
899,900,Yukinari Sugawara,MF,jp Japan,25,1.de Werder Bremen,2000,4,1,148,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,580bcd18,Starter
171,172,Lamine Camara,MF,sn Senegal,22,1.fr Monaco,2004,4,3,248,...,1,0,0.00,0.36,0.36,0.00,0.36,Matches,19c2ffa4,Starter
307,308,Enzo Fernández,MF,ar Argentina,25,1.eng Chelsea,2001,7,7,659,...,2,1,0.27,0.00,0.27,0.27,0.27,Matches,5ff4ab71,Starter
677,678,Benjamin Nygren,MF,se Sweden,24,1.sct Celtic,2001,4,2,130,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,d6ebf67f,Starter
1015,1016,John Yeboah,MF,ec Ecuador,25,2.it Venezia,2000,4,4,311,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,8dfdc6c3,Starter
216,217,Andrés Cubas,MF,py Paraguay,30,1.us Vancouver,1996,5,5,480,...,1,0,0.00,0.00,0.00,0.00,0.00,Matches,9b40a6ea,Starter
428,429,Hwang In-beom,MF,kr Korea Republic,29,1.nl Feyenoord,1996,3,3,263,...,0,0,0.34,0.34,0.68,0.34,0.68,Matches,92fa5d28,Starter
78,79,Carlens Arcus,MFDF,ht Haiti,29,1.fr Angers,1996,3,2,146,...,1,0,0.00,0.00,0.00,0.00,0.00,Matches,5e837126,Starter
808,809,Elias Saad,MFFW,tn Tunisia,26,2.de Hannover 96,1999,2,2,116,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,78a2284f,Starter
39,40,Jordy Alcivar,MF,ec Ecuador,26,1.ec Independiente,1999,1,1,45,...,1,0,0.00,0.00,0.00,0.00,0.00,Matches,6e98c19f,Starter
477,478,Jesper Karlström,MF,se Sweden,30,1.it Udinese,1995,2,2,138,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,e0a1f4eb,Starter
554,555,Riyad Mahrez,MF,dz Algeria,35,1.sa Al-Ahli,1991,4,3,262,...,0,0,0.69,0.34,1.03,0.69,1.03,Matches,892d5bb1,Starter
306,307,Bruno Fernandes,MF,pt Portugal,31,1.eng Manchester Utd,1994,5,5,422,...,0,0,0.00,0.21,0.21,0.00,0.21,Matches,507c7bdf,Starter
566,567,Mahmoud Al-Mardi,MF,jo Jordan,32,1.jo Al-Hussein SC,1993,3,1,130,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,1eedc1ea,Starter
460,461,Edmilson Junior,MFFW,qa Qatar,31,1.qa Al Duhail SC,1994,3,3,210,...,0,0,0.00,0.43,0.43,0.00,0.43,Matches,620764f4,Starter
486,487,Bilal El Khannouss,MFFW,ma Morocco,22,1.de Stuttgart,2004,6,6,461,...,1,0,0.00,0.00,0.00,0.00,0.00,Matches,f7042636,Starter
144,145,Ayyoub Bouaddi,MF,ma Morocco,18,1.fr Lille,2007,5,5,381,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,8006228f,Starter
199,200,Brian Cipenga,MFFW,cd Congo DR,28,2.es Castellón,1998,2,2,146,...,0,0,0.62,0.00,0.62,0.62,0.62,Matches,e4787d6f,Starter
662,663,Pedro Neto,MF,pt Portugal,26,1.eng Chelsea,2000,5,5,350,...,0,0,0.00,0.26,0.26,0.00,0.26,Matches,7ba2eaa9,Starter
337,338,Mohammad Ghorbani,MF,ir IR Iran,25,1.ae Al-Wahda FC,2001,1,1,90,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,4a078e18,Starter
108,109,Ivan Bašić,MF,ba Bosnia–Herz,24,1.kz FC Astana,2002,3,2,179,...,0,0,0.00,0.50,0.50,0.00,0.50,Matches,9b0a0d51,Starter
336,337,Saman Ghoddos,MF,ir IR Iran,32,1.ae Al-Ittihad Kalba,1993,3,3,208,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,f7b1d4e0,Starter
872,873,Bernardo Silva,MF,pt Portugal,31,1.eng Manchester City,1994,4,1,97,...,2,0,0.00,0.00,0.00,0.00,0.00,Matches,3eb22ec9,Starter
593,594,John McGinn,MF,sct Scotland,31,1.eng Aston Villa,1994,3,3,259,...,0,0,0.35,0.00,0.35,0.35,0.35,Matches,90f91999,Starter
24,25,Akram Afif,FWMF,qa Qatar,29,1.qa Al Sadd,1996,3,3,238,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,fd53d9e7,Starter
631,632,Kim Moon-hwan,MF,kr Korea Republic,30,1.kr Daejeon Hana,1995,1,1,70,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,6bce7dd8,Starter
840,841,Xaver Schlager,MF,at Austria,28,1.de RB Leipzig,1997,4,4,238,...,0,0,0.00,0.38,0.38,0.00,0.38,Matches,8f056768,Starter
1019,1020,Seol Young-woo,MF,kr Korea Republic,27,1.rs Red Star,1998,3,3,250,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,8e577e1d,Starter
1030,1031,Ramiz Zerrouki,MF,dz Algeria,28,1.nl Twente,1998,3,2,111,...,1,0,0.00,0.00,0.00,0.00,0.00,Matches,c762b1a6,Starter
240,241,Louicius Deedson,MF,ht Haiti,25,1.us FC Dallas,2001,3,1,112,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,f7059bb1,Starter
18,19,Tyler Adams,MF,us USA,27,1.eng Bournemouth,1999,4,4,341,...,1,0,0.00,0.00,0.00,0.00,0.00,Matches,2b09d998,Starter
291,292,Saeid Ezatolahi,MF,ir IR Iran,29,1.ae Al-Ahli Dubai FC,1996,3,3,264,...,2,0,0.00,0.00,0.00,0.00,0.00,Matches,314d95ac,Starter
703,704,Azzedine Ounahi,MF,ma Morocco,26,1.es Girona,2000,6,5,435,...,1,0,0.41,0.00,0.41,0.41,0.41,Matches,83299cc0,Starter
245,246,Sergiño Dest,MF,us USA,25,1.nl PSV,2000,5,4,297,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,5976f83e,Starter
124,125,Anis Ben Slimane,MFFW,tn Tunisia,25,2.eng Norwich City,2001,3,3,240,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,9ade9ce1,Starter
597,598,Kenny McLean,MF,sct Scotland,34,2.eng Norwich City,1992,3,1,118,...,1,0,0.00,0.00,0.00,0.00,0.00,Matches,471f16b3,Starter
897,898,Luka Sučić,FWMF,hr Croatia,23,1.es Real Sociedad,2002,1,0,19,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,1e1378e1,Substitute
783,784,Richard Ríos,MF,co Colombia,26,1.pt Benfica,2000,5,0,140,...,1,0,0.00,0.00,0.00,0.00,0.00,Matches,72da065d,Substitute
873,874,Éderson Silva,MF,br Brazil,26,1.it Atalanta,1999,2,0,22,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,a9202def,Substitute
356,357,Pascal Groß,DFMF,de Germany,34,1.eng Brighton,1991,1,0,18,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,8aec0537,Substitute
656,657,Duckens Nazon,FWMF,ht Haiti,32,1.ir Esteghlal,1994,1,0,24,...,1,0,0.00,0.00,0.00,0.00,0.00,Matches,20e87a42,Substitute
210,211,Samu Costa,MF,pt Portugal,25,1.es Mallorca,2000,1,0,21,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,76c2a023,Substitute
1013,1014,Yannick,MF,cv Cabo Verde,30,2.pt Farense,1995,2,0,32,...,0,0,0.00,2.81,2.81,0.00,2.81,Matches,6246aa55,Substitute
343,344,Andrés Gómez,MF,co Colombia,23,1.br Vasco da Gama,2002,1,0,1,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,76a82373,Substitute
686,687,Noah Okafor,FWMF,ch Switzerland,26,1.eng Leeds United,2000,1,0,20,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,ca607d59,Substitute
948,949,Kai Trewin,DFMF,au Australia,25,1.us NYCFC,2001,1,0,75,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,1ab3d134,Substitute
161,162,Dženis Burnić,MF,ba Bosnia–Herz,28,2.de Karlsruher,1998,2,0,16,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,0dabaf14,Substitute
567,568,Jearl Margaritha,FWMF,cw Curaçao,26,2.be Beveren,2000,2,0,41,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,be915a68,Substitute
105,106,Valentín Barco,DFMF,ar Argentina,21,1.fr Strasbourg,2004,1,0,20,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,b9f282ec,Substitute
435,436,Jamshid Iskanderov,FWMF,uz Uzbekistan,32,1.uz Neftchi FK,1993,1,0,9,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,3b8abe7c,Substitute
181,182,Jens Castrop,MF,kr Korea Republic,22,1.de Gladbach,2003,1,0,45,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,03fee7de,Substitute
217,218,Cucho,FWMF,co Colombia,27,1.es Real Betis,1999,2,0,50,...,0,0,0.00,1.80,1.80,0.00,1.80,Matches,71b47ab9,Substitute
875,876,Dominique Simon,MF,ht Haiti,25,1.sk 1. FC Tatran Prešov B,2000,2,0,56,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,ffd8e8c5,Substitute
709,710,Kendry Páez,MF,ec Ecuador,19,1.ar River Plate,2007,1,0,12,...,1,0,0.00,0.00,0.00,0.00,0.00,Matches,f3bb9f59,Substitute
1003,1004,Patrick Wimmer,FWMF,at Austria,25,1.de Wolfsburg,2001,2,0,21,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,cb11b429,Substitute
116,117,Maximilian Beier,FWMF,de Germany,23,1.de Dortmund,2002,1,0,27,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,5db45ee5,Substitute
491,492,Justin Kluivert,FWMF,nl Netherlands,27,1.eng Bournemouth,1999,2,0,27,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,4c3a6744,Substitute
141,142,Theo Bongonda,FWMF,cd Congo DR,30,1.ru Spartak Moscow,1995,2,0,34,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,0da6a13e,Substitute
79,80,Max Arfsten,MF,us USA,25,1.us Columbus Crew,2001,1,0,1,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,668f881e,Substitute
64,65,Youssef Amyn,MF,iq Iraq,22,1.cy AEK Larnaca,2003,1,0,31,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,10c12f22,Substitute
220,221,Findlay Curtis,MF,sct Scotland,19,1.sct Kilmarnock,2006,2,0,9,...,1,0,0.00,0.00,0.00,0.00,0.00,Matches,e2a68b89,Substitute
1009,1010,Haji Wright,FWMF,us USA,28,2.eng Coventry City,1998,2,0,2,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,91cd37b7,Substitute
672,673,Tyrese Noslin,MF,cw Curaçao,23,1.nl Telstar,2002,1,0,14,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,c3709bd2,Substitute
360,361,Evann Guessand,FWMF,ci Côte d'Ivoire,24,1.eng Crystal Palace,2001,2,0,17,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,b73f17f8,Substitute
892,893,Angelo Stiller,MF,de Germany,25,1.de Stuttgart,2001,1,0,45,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,3b1ed320,Substitute
1029,1030,Besfort Zeneli,MF,se Sweden,23,1.be Union SG,2002,2,0,60,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,6be253bf,Substitute
931,932,Brandon Thomas-Asante,FWMF,gh Ghana,27,2.eng Coventry City,1998,2,0,53,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,fb152f96,Substitute
509,510,Brandley Kuwas,FWMF,cw Curaçao,33,1.nl Volendam,1992,1,0,1,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,42c94967,Substitute
406,407,Jordan Henderson,MF,eng England,35,1.eng Brentford,1990,1,0,7,...,1,0,0.00,0.00,0.00,0.00,0.00,Matches,935e6b8f,Substitute
553,554,Hadj Mahmoud,MF,tn Tunisia,26,1.ch Lugano,2000,2,0,43,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,081048c2,Substitute
21,22,Simon Adingra,FWMF,ci Côte d'Ivoire,24,1.fr Monaco,2002,1,0,16,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,4dcec659,Substitute
652,653,Yūto Nagatomo,DFMF,jp Japan,39,1.jp FC Tokyo,1986,1,0,16,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,4b6960d2,Substitute
308,309,Matias Fernandez-Pardo,FWMF,be Belgium,21,1.fr Lille,2005,3,0,44,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,0cdb6a2a,Substitute
297,298,Marko Farji,MF,iq Iraq,22,2.it Venezia,2004,2,0,54,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,e046cff6,Substitute
447,448,Amer Jamous,MF,jo Jordan,23,1.iq Al-Zawra'a SC,2002,1,0,15,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,32d4f1e1,Substitute
1006,1007,Axel Witsel,DFMF,be Belgium,37,1.es Girona,1989,2,0,33,...,1,0,0.00,0.00,0.00,0.00,0.00,Matches,5dfc6ad5,Substitute
189,190,Luis Chávez,MF,mx Mexico,30,1.ru Dynamo Moskva,1996,1,0,25,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,e50949ea,Substitute
934,935,Marcus Thuram,FWMF,fr France,28,1.it Inter,1997,1,0,1,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,6f8cd6d0,Substitute
796,797,Godfried Roemeratoe,MF,cw Curaçao,26,2.nl RKC Waalwijk,1999,1,0,7,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,a646b710,Substitute
643,644,Miro Muheim,DFMF,ch Switzerland,28,1.de Hamburger SV,1998,3,0,87,...,1,0,0.00,0.00,0.00,0.00,0.00,Matches,844c6a91,Substitute
882,883,Ramón Sosa,FWMF,py Paraguay,26,1.br Palmeiras,1999,1,0,12,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,2d3417a1,Substitute
255,256,Ismael Díaz,FWMF,pa Panama,29,1.mx León,1997,2,0,37,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,f2a276d1,Substitute
544,545,Awer Mabil,FWMF,au Australia,30,2.es Castellón,1995,1,0,30,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,922da988,Substitute
173,174,İrfan Can Kahveci,MF,tr Türkiye,30,1.tr Kasımpaşa,1995,1,0,1,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,d2800f47,Substitute
849,850,Ken Sema,FWMF,se Sweden,32,1.cy Pafos FC,1993,1,0,16,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,1770bd68,Substitute
441,442,Cedric Itten,FWMF,ch Switzerland,29,2.de Düsseldorf,1996,3,0,42,...,0,0,0.00,0.00,0.00,0.00,0.00,Matches,ef233486,Substitute